/**
 * Audit spec for: Login
 * URL: https://www.saucedemo.com
 *
 * Generated by ATG – Automation Test Generator
 * This spec runs the full Audit Engine for every field on the page:
 *   1. DOMAnalyzer   – passive DOM scan
 *   2. FieldClassifier – categorize fields
 *   3. RuleEvaluator  – declarative rule checks
 *   4. DataStrategyEngine + FieldExperimentRunner – behavioral tests
 *   5. InferenceEngine – determine maturity state
 *   6. ScoringEngine  – calculate FQI and SMI
 *   7. ReportBuilder  – write HTML report
 *
 * Configuration:
 *   Copy .env.example to .env and fill in your values before running.
 *   Override the page URL:  PAGE_URL_LOGIN=https://your-env.example.com/page
 */

import * as dotenv from 'dotenv';
dotenv.config();

import { test, expect } from '@playwright/test';
import * as path from 'path';
import * as fs from 'fs';
import { DOMAnalyzer } from '../audit-engine/DOMAnalyzer';
import { FieldClassifier } from '../audit-engine/FieldClassifier';
import { RuleEvaluator } from '../audit-engine/RuleEvaluator';
import { DataStrategyEngine } from '../audit-engine/DataStrategyEngine';
import { FieldExperimentRunner } from '../audit-engine/FieldExperimentRunner';
import { InferenceEngine } from '../audit-engine/InferenceEngine';
import { ScoringEngine } from '../audit-engine/ScoringEngine';
import { CPGenerator } from '../audit-engine/CPGenerator';
import { ReportBuilder } from '../audit-engine/ReportBuilder';

// Allow overriding the page URL via .env (e.g. PAGE_URL_LOGIN=https://staging.example.com)
const PAGE_URL = process.env.PAGE_URL_LOGIN || "https://www.saucedemo.com";
const PAGE_NAME = "Login";
const REPORT_DIR = path.resolve('reports', 'auditing');

// Fields captured during DOM Capture in ATG wizard
const capturedFields = [
    { name: "Username", selector: "#user-name", type: "input", placeholder: "Username" },
    { name: "Password", selector: "#password", type: "password", placeholder: "Password" }
];

// Custom CSS error class tokens configured in the ATG wizard for this project's design system.
// These are merged with the standard error tokens inside FieldExperimentRunner.
// Empty array = use only the built-in standard tokens.
const CUSTOM_ERROR_CLASSES: string[] = [];

test.use({
  baseURL: PAGE_URL,
});

test.describe(`Audit: ${PAGE_NAME}`, () => {
  test('Full field audit and report generation', async ({ page }) => {
    // ── ARRANGE ──────────────────────────────────────────────────
    await page.goto(PAGE_URL, { waitUntil: 'domcontentloaded' });

    // Detect an anti-bot challenge widget once, at page load. Cloudflare Turnstile,
    // reCAPTCHA and hCaptcha all block the real form submit until their challenge is
    // resolved — something Playwright cannot do like a human would. When present,
    // SUBMIT CPs that failed WITHOUT the request ever reaching the network (see the
    // reclassification below) are not real findings about the form's validation —
    // they're an artifact of the challenge, and get marked 'inconclusive' instead of
    // 'fail'. Detected once per page (not re-checked per field/CP) — covers the common
    // case of a widget visible in the initial DOM.
    //
    // These widgets load asynchronously (an external <script> fetches from
    // challenges.cloudflare.com/recaptcha/hcaptcha and injects the iframe into the DOM after
    // the fact) — 'domcontentloaded' fires before that script has necessarily run, so a single
    // synchronous check right after goto() can miss a challenge that is genuinely present a
    // moment later. Poll for up to 3s (checking every 200ms) so the vast majority of real
    // widgets are caught, without materially slowing down pages that have no challenge at all
    // (loop exits immediately on the first successful detection).
    //
    // Turnstile's actual widget iframe (challenges.cloudflare.com/cdn-cgi/challenge-platform/...)
    // lives inside a CLOSED shadow root (<template shadowrootmode="closed">) — confirmed against
    // a real dev.zinior.com/login capture. A closed shadow root is unreachable from JS entirely
    // (querySelector can't pierce it, and `.shadowRoot` returns null by design), so the iframe
    // selectors below can never match in practice for real Turnstile deployments.
    // `[id="cf-turnstile"]` / `[id^="cf-turnstile-"]` are NOT part of Cloudflare's contract —
    // they only matched because the pilot site (Zinior) happened to name its own container div
    // "cf-turnstile". A different integration (e.g. ATG's own login, whose container is an
    // unnamed `<div ref={...}>`) renders Turnstile without ever creating that id, and the
    // challenge went undetected there (18 CPs wrongly scored as real failures instead of
    // 'inconclusive'). The one element Cloudflare's own script ALWAYS injects into the
    // container regardless of its id/class — confirmed on both dev.zinior.com and ATG's own
    // login — is a hidden input named `cf-turnstile-response` (the token field the form submits
    // for verification); that is the truly universal, contract-guaranteed signal and is checked
    // first. The id/class selectors are kept as defense-in-depth for sites that do use that
    // naming convention; the iframe selectors are kept as a fallback for any integration that
    // (unusually) renders Turnstile in an open/light-DOM iframe instead of the standard
    // closed-shadow embed.
    const CHALLENGE_SELECTORS = [
      'input[name="cf-turnstile-response"]',
      '[id="cf-turnstile"]',
      '[id^="cf-turnstile-"]',
      'iframe[src*="challenges.cloudflare.com"]',
      '.cf-turnstile',
      '.g-recaptcha',
      'iframe[src*="recaptcha"]',
      '.h-captcha',
      'iframe[src*="hcaptcha.com"]',
    ];
    let _challengeDetected = false;
    const _challengeDeadline = Date.now() + 3000;
    while (!_challengeDetected && Date.now() < _challengeDeadline) {
      _challengeDetected = await page.evaluate((selectors) => {
        return selectors.some((sel) => document.querySelector(sel) !== null);
      }, CHALLENGE_SELECTORS).catch(() => false);
      if (!_challengeDetected) {
        await page.waitForTimeout(200).catch(() => {});
      }
    }

    // ── ACT: Run audit engine ─────────────────────────────────────
    const domAnalyzer = new DOMAnalyzer();
    const classifier = new FieldClassifier();
    const ruleEvaluator = new RuleEvaluator();
    const dataStrategy = new DataStrategyEngine();
    const experimentRunner = new FieldExperimentRunner(CUSTOM_ERROR_CLASSES);
    const inferenceEngine = new InferenceEngine();
    const scoringEngine = new ScoringEngine();
    const cpGenerator = new CPGenerator();
    const reportBuilder = new ReportBuilder();

    // 1. Extract fields from live DOM (validates captured fields are still present)
    const liveFields = await domAnalyzer.extractFields(page);

    // 2. Merge with wizard-captured fields (prefer locators from live DOM, fallback to captured)
    const mergedFields = capturedFields.length > 0 ? capturedFields.map(cf => {
      const tagName = cf.type === 'textarea' ? 'textarea' : cf.type === 'select' ? 'select' : 'input';
      const id = cf.selector.startsWith('#') ? cf.selector.slice(1) : undefined;
      const element = {
        locator: cf.selector,
        tagName,
        type: cf.type,
        name: cf.name,
        id,
        required: (cf as any).required ?? false,
        autocomplete: (cf as any).autocomplete ?? undefined,
        maxLength: (cf as any).maxLength ?? undefined,
        pattern: (cf as any).pattern ?? undefined,
        classNames: (cf as any).classNames ?? '',
        placeholder: (cf as any).placeholder ?? undefined,
        label: (cf as any).label ?? cf.name,
      };
      // If the user manually set a field type in the wizard, honour it; otherwise classify
      const inferredCategory: string = (cf as any).auditFieldType
        ? (cf as any).auditFieldType
        : classifier.classify({ element, inferredCategory: 'UNKNOWN' });
      return { element, inferredCategory };
    }) : liveFields;

    const fieldAuditResults: any[] = [];
    let _totalInconclusive = 0; // accumulated across all fields, for the executive summary

    // Flat, structured list of every individual finding (declarative + behavioral) across all
    // fields — written to disk as JSON after the test so TestRunPreviewService can persist each
    // one to `audit_findings` (console.log lines are for live SSE progress only, not parsed for
    // structured persistence).
    const allFindingsFlat: Array<{
      fieldName: string;
      fieldType: string;
      ruleId: string;
      severity: string;
      status: 'pass' | 'fail' | 'inconclusive';
      detail: string;
      // Raw network/DOM evidence for Behavioral findings only (undefined for Declarative) — lets
      // TestRunPreviewService persist it to audit_findings.evidence so future diagnostics don't
      // have to re-run the audit just to see requestAttempted/backendErrorReturned/etc.
      evidence?: Record<string, unknown>;
    }> = [];

    // ── GLOBAL ROUTE INTERCEPTOR ─────────────────────────────────────────────
    // Block all mutating API calls (POST/PUT/PATCH/DELETE) from the audit page's
    // origin. This prevents form submissions from navigating the page during
    // behavioral experiments while still letting us observe whether a request
    // was attempted. Static assets (CDN images, fonts, scripts) are not affected.
    //
    // _currentRuleExpectsAcceptance is updated right before each runExperiment() call
    // (see the loop below) so the interceptor knows whether the CP currently running is
    // an ALLOWS_SUBMIT acceptance case (valid payload) or a rejection case (invalid/malicious
    // payload). Without this, every fetch/xhr submission always got a synthetic 422 — which
    // made every ALLOWS_SUBMIT rule impossible to ever pass on SPAs that submit via fetch/xhr,
    // regardless of how valid the payload actually was (false positive baked into the engine).
    let _currentRuleExpectsAcceptance = false;
    const _auditOrigin = new URL(PAGE_URL).origin;
    const _blockedMethods = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);
    await page.route(`${_auditOrigin}/**`, async (route) => {
      const req = route.request();
      if (_blockedMethods.has(req.method())) {
        if (req.resourceType() === 'document') {
          // Traditional form submit (navigation): use fulfill() instead of abort().
          // abort('blockedbyclient') races with HTTP 302 redirects — if the server
          // responds with a redirect before the abort lands, Chromium follows it and
          // destroys the page context, making later page operations throw
          // "Target page, context or browser has been closed".
          // fulfill() short-circuits the request entirely inside Chromium's routing
          // layer before it leaves the browser, so no real server response (including
          // a 302 redirect) can interfere. The synthetic 200 keeps the page alive
          // and on the same URL. The X-ATG-Intercepted header lets FieldExperimentRunner
          // identify this response and record the correct audit signals.
          await route.fulfill({
            status: 200,
            contentType: 'text/html',
            headers: { 'X-ATG-Intercepted': 'document' },
            body: '',
          });
        } else if (['fetch', 'xhr'].includes(req.resourceType())) {
          // AJAX — synthetic response so requestAttempted is observable without ever hitting
          // the real backend (destructive payloads like SQLi/XSS must never reach a third-party
          // server). For ALLOWS_SUBMIT acceptance CPs, fulfill with 200 instead of 422 — otherwise
          // a valid payload could never be distinguished from an invalid one.
          if (_currentRuleExpectsAcceptance) {
            await route.fulfill({ status: 200, contentType: 'application/json', body: '{"auditing":"intercepted","message":"audit-ok"}' });
          } else {
            await route.fulfill({ status: 422, contentType: 'application/json', body: '{"auditing":"intercepted","message":"audit-blocked"}' });
          }
        } else {
          await route.continue();
        }
      } else {
        await route.continue();
      }
    });

    const _totalFields = mergedFields.length;
    for (let _fi = 0; _fi < mergedFields.length; _fi++) {
      const field = mergedFields[_fi];
      // 3. Get rules for this field category (specific + UNKNOWN baseline)
      const rules = ruleEvaluator.getRulesForField(field);

      // 4. Evaluate Declarative rules — emits a Finding for every rule (passed or failed)
      const declarativeFindings = ruleEvaluator.evaluateDeclarative(field, rules);

      // 5. Run Behavioral experiments — run ALL rules for complete coverage.
      // No sampling cap: every available CP must be evaluated to avoid false negatives.
      const behavioralRules = rules.filter(r => r.type === 'Behavioral');
      const severityOrder: Record<string, number> = { Critical: 4, Error: 3, Warning: 2, Info: 1 };
      const selectedBehavioral = behavioralRules.sort((a, b) =>
        (severityOrder[b.severity] ?? 0) - (severityOrder[a.severity] ?? 0)
      );

      console.log(`\n[${_fi + 1}/${_totalFields}] Field: ${field.element.locator} (${field.inferredCategory}) — ${declarativeFindings.length} declarative, ${selectedBehavioral.length} behavioral`);

      const behavioralFindings = [];
      for (let _bi = 0; _bi < selectedBehavioral.length; _bi++) {
        const rule = selectedBehavioral[_bi];
        const payload = dataStrategy.resolvePayload(field, rule);
        if (payload !== null) {
          // BLUR experiments require a clean DOM: a prior SUBMIT experiment may have left
          // error messages in the DOM (e.g. <p class="text-red-500">) that would falsely
          // satisfy the domErrorClassDetected check, producing false negatives.
          // Reloading before each BLUR experiment guarantees a pristine starting state.
          if (rule.requiredInteractionType === 'BLUR') {
            try {
              await page.goto(PAGE_URL, { waitUntil: 'domcontentloaded', timeout: 15000 });
            } catch { /* ignore navigation errors and page-closed errors */ }
          }
          console.log(`  [${_bi + 1}/${selectedBehavioral.length}] ${rule.requiredInteractionType} ${rule.id} — payload: ${String(payload).slice(0, 40)}`);
          _currentRuleExpectsAcceptance = (rule.expectedBehavior || []).includes('ALLOWS_SUBMIT');
          try {
            const rawResult = await experimentRunner.runExperiment(page, field, rule, payload);
            const finding = inferenceEngine.generateBehavioralFinding(rule, rawResult);
            // Reclassify: a SUBMIT finding that failed because the request never reached the
            // network is indistinguishable from "the challenge blocked it" vs "the frontend
            // correctly blocked an invalid payload" UNLESS we know a challenge is present. Only
            // reclassify when the request never fired — a finding whose request DID reach the
            // backend (requestAttempted:true) is unaffected by the challenge and stays as-is.
            if (_challengeDetected && !finding.passed && rule.requiredInteractionType === 'SUBMIT' && !rawResult.requestAttempted) {
              finding.isInconclusive = true;
            }
            behavioralFindings.push(finding);
            console.log(`         → ${finding.isInconclusive ? '⚠ INCONCLUSIVE (challenge detected)' : finding.passed ? '✓ PASS' : '✗ FAIL'}`);
          } catch {
            // Continue if experiment fails for a field
            console.log(`         → ✗ ERROR (experiment threw)`);
          }
          // Recover page if a form submission caused navigation away from the audit target.
          // page.url() itself throws when the context is closed, so we must try/catch it.
          try {
            if (page.url() !== PAGE_URL) {
              await page.goto(PAGE_URL, { waitUntil: 'domcontentloaded', timeout: 15000 });
            }
          } catch { /* page context was destroyed — next experiment's goto() will re-establish state */ }
        }
      }

      // 6. Infer maturity state — exclude isInconclusive findings from scoring: they are not
      // evidence of the form's real validation, they are an artifact of the anti-bot challenge.
      const scorableBehavioral = behavioralFindings.filter(f => !f.isInconclusive);
      const allFindings = [...declarativeFindings, ...behavioralFindings]; // unfiltered — used for reporting/persistence
      const scorableFindings = [...declarativeFindings, ...scorableBehavioral];
      const maturityState = inferenceEngine.determineMaturityState(field, declarativeFindings, scorableBehavioral);
      const _passed = allFindings.filter(f => f.passed).length;
      const _failed = allFindings.filter(f => !f.passed && !f.isInconclusive).length;
      const _inconclusive = allFindings.filter(f => f.isInconclusive).length;
      _totalInconclusive += _inconclusive;
      console.log(`  → ${maturityState} | ${_passed} passed, ${_failed} failed, ${_inconclusive} inconclusive`);

      for (const f of allFindings) {
        allFindingsFlat.push({
          fieldName: field.element.name || field.element.locator,
          fieldType: field.inferredCategory,
          ruleId: f.ruleId,
          severity: f.severity,
          status: f.isInconclusive ? 'inconclusive' : (f.passed ? 'pass' : 'fail'),
          detail: f.isInconclusive
            ? `Inconclusive: an anti-bot challenge (Cloudflare Turnstile/reCAPTCHA/hCaptcha) blocked the form submit before it could be observed. ${f.errorMessage || f.ruleDescription || ''}`.trim()
            : (f.errorMessage || f.ruleDescription || ''),
          evidence: f.interactionEvidence as unknown as Record<string, unknown> | undefined,
        });
      }

      // 7. Calculate per-field FQI (SMI global is computed after all fields are processed) —
      // uses scorableFindings (isInconclusive excluded), not the unfiltered allFindings.
      const fqi = scoringEngine.calculateFQI(scorableFindings);
      const smi = fqi; // placeholder — not used individually; global SMI computed below

      // 8. Generate checkpoint
      const cp = cpGenerator.generateCheckpoint({
        fieldId: field.element.locator,
        fieldName: field.element.name || field.element.locator,
        fieldCategory: field.inferredCategory,
        maturityState,
        findings: allFindings,
        fqi,
        smi,
      }, fieldAuditResults.length);

      fieldAuditResults.push(cp);

      // ── ASSERT: Every field must be audited (no crash) ───────────
      expect(cp).toBeDefined();
      expect(fqi).toBeGreaterThanOrEqual(0);
    }

    // Remove global route interceptor before generating the report.
    // Wrapped in try/catch: { behavior: 'ignoreErrors' } only suppresses route handler errors,
    // not the "Target closed" IPC error thrown when the page context was destroyed by a navigation race.
    try {
      await page.unrouteAll({ behavior: 'ignoreErrors' });
    } catch { /* page context already destroyed — routes were cleaned up by Playwright */ }

    // Write structured findings JSON next to the Playwright JSON reporter output
    // (test-results/results.json) so TestRunPreviewService can locate and persist both
    // from the same known directory.
    const findingsDir = path.resolve('test-results');
    fs.mkdirSync(findingsDir, { recursive: true });
    fs.writeFileSync(
      path.join(findingsDir, 'audit-findings.json'),
      JSON.stringify(allFindingsFlat),
      'utf-8',
    );

    // 8. Compute global SMI across all fields (includes ContextPenalty for EMAIL/PASSWORD ABSENT)
    const globalSMI = scoringEngine.calculateSMI(
      fieldAuditResults.map(cp => ({
        fqi: cp.metadata.fqi,
        inferredCategory: cp.metadata.fieldCategory,
        maturityState: cp.metadata.maturityState,
      }))
    );

    // 9. Build executive summary and generate HTML report
    const summary = reportBuilder.buildExecutiveSummary(fieldAuditResults, globalSMI, _challengeDetected, _totalInconclusive);
    const html = reportBuilder.generateReport(summary, fieldAuditResults);

    // Write HTML report
    fs.mkdirSync(REPORT_DIR, { recursive: true });
    const reportFile = path.join(REPORT_DIR, `${PAGE_NAME.replace(/[^a-zA-Z0-9]/g, '-')}-audit-report.html`);
    fs.writeFileSync(reportFile, html, 'utf-8');

    console.log(`[Audit] Report written to: ${reportFile}`);
    console.log(`[Audit] Total fields: ${fieldAuditResults.length}`);
    console.log(`[Audit] Global SMI: ${summary.globalSMI?.toFixed(2)}`);

    // ── WRITE Markdown summary ────────────────────────────────────
    const mdFile = path.join(REPORT_DIR, `${PAGE_NAME.replace(/[^a-zA-Z0-9]/g, '-')}-test-report-summary.md`);
    const _gradeEmoji = (g: string) => ({ A: '🏆', B: '✅', C: '⚠️', D: '🔶', F: '❌' } as Record<string,string>)[g] ?? '—';
    const _matLabel: Record<string, string> = {
      ROBUST_FULL_STACK: 'Robust Full Stack', FRONTEND_ONLY: 'Frontend Only',
      BACKEND_ONLY: 'Backend Only', WEAK_VALIDATION: 'Weak Validation',
      ABSENT: 'Absent', FALSE_POSITIVE: 'False Positive',
    };
    const _distRows = Object.entries(summary.maturityDistribution).map(([st, n]) => {
      const pct = summary.totalFields > 0 ? Math.round((n / summary.totalFields) * 100) : 0;
      return `| ${_matLabel[st] ?? st} | ${n} | ${pct}% |`;
    }).join('\n');
    const _fieldRows = fieldAuditResults.map(cp => {
      const _f = (cp.metadata?.findings ?? []) as any[];
      const _fail = _f.filter(f => !f.passed).length;
      const _pass = _f.filter(f => f.passed).length;
      const _icon = cp.status === 'PASS' ? '✅ PASS' : cp.status === 'WARN' ? '⚠️ WARN' : '❌ FAIL';
      return `| \`${cp.targetElement}\` | ${cp.metadata?.fieldCategory ?? '—'} | ${_matLabel[cp.metadata?.maturityState] ?? cp.metadata?.maturityState ?? '—'} | ${cp.metadata?.fqi ?? '—'} | ${_f.length} | ${_pass} | ${_fail} | ${_icon} |`;
    }).join('\n');
    const _critRows: string[] = [];
    for (const cp of fieldAuditResults) {
      for (const f of (cp.metadata?.findings ?? [] as any[]).filter((f: any) => !f.passed && (f.severity === 'Critical' || f.severity === 'Error'))) {
        _critRows.push(`| \`${cp.targetElement}\` | \`${f.ruleId ?? '—'}\` | **${f.severity}** | ${f.ruleDescription ?? '—'} |`);
      }
    }
    const _critSection = _critRows.length > 0
      ? `| Field | Rule ID | Severity | Description |\n|-------|---------|----------|-------------|\n${_critRows.join('\n')}`
      : '✅ No critical or error-level violations found.';
    const mdContent = [
      `# Audit Report Summary — ${PAGE_NAME}`,
      '',
      `**URL:** ${PAGE_URL}`,
      `**Generated:** ${new Date().toISOString()}`,
      `**Report:** reports/auditing/${PAGE_NAME.replace(/[^a-zA-Z0-9]/g, '-')}-audit-report.html`,
      '',
      '---',
      '',
      '## Overall Score',
      '',
      '| Metric | Value |',
      '|--------|-------|',
      `| Grade | ${_gradeEmoji(summary.grade)} ${summary.grade} |`,
      `| Global SMI | ${summary.globalSMI} / 100 |`,
      `| Avg FQI | ${summary.avgFQI} / 100 |`,
      `| Fields Audited | ${summary.totalFields} |`,
      `| ✅ Passed | ${summary.passedFields} |`,
      `| ⚠️ Warned | ${summary.warnFields} |`,
      `| ❌ Failed | ${summary.failedFields} |`,
      '',
      '---',
      '',
      '## Maturity Distribution',
      '',
      '| State | Count | % |',
      '|-------|-------|---|',
      _distRows,
      '',
      '---',
      '',
      '## Field Results',
      '',
      '| Field | Category | Maturity State | FQI | Rules | Passed | Failed | Status |',
      '|-------|----------|----------------|-----|-------|--------|--------|--------|',
      _fieldRows,
      '',
      '---',
      '',
      '## Critical Violations',
      '',
      _critSection,
      '',
      '---',
      '',
      '*Generated by ATG – Automation Test Generator*',
    ].join('\n');
    fs.writeFileSync(mdFile, mdContent, 'utf-8');
    console.log(`[Audit] Summary written to: ${mdFile}`);

    // ── ASSERT: Report was successfully written ───────────────────
    expect(fs.existsSync(reportFile)).toBe(true);
    expect(fs.existsSync(mdFile)).toBe(true);
    expect(fieldAuditResults.length).toBeGreaterThan(0);
  });
});
